# Generated by Django 3.1.3 on 2021-02-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_name', models.CharField(max_length=100)),
                ('Employee_department', models.CharField(choices=[('Python', 'Python'), ('Php', 'Php'), ('Java', 'Java'), ('Node', 'Nodes')], max_length=100)),
            ],
        ),
    ]
